### ISSUE TITLE
heart beat problem in react-native

### ISSUE THREAD

**Issue by shinigami1992** [jmesnil/stomp-websocket#133]
Hi. First of all, thanks for your awesome library.

I have a browser app with sockjs and stompjs which is working fine as excepted.

When I started to develop same app in react-native environment, I face some issues about heart-beats. It seems client doesn't send heat-beat (>>>PING requests) anymore.

and I get following error after heartbeat time passed.

`Whoops! Lost connection to ...`

I'm using latest version of _stompjs_ and import it in my code this way:

`var Stomp = require('stompjs/lib/stomp.js').Stomp;`

```
06-01 13:02:56.416  3557  4263 I ReactNativeJS: >>> CONNECT
06-01 13:02:56.416  3557  4263 I ReactNativeJS: X-Suptory-Id:58c57aced34ed95c7c5613e1
06-01 13:02:56.416  3557  4263 I ReactNativeJS: accept-version:1.1,1.0
06-01 13:02:56.416  3557  4263 I ReactNativeJS: heart-beat:10000,10000
06-01 13:02:56.466  3557  4263 I ReactNativeJS:
06-01 13:02:56.466  3557  4263 I ReactNativeJS: <<< CONNECTED
06-01 13:02:56.466  3557  4263 I ReactNativeJS: heart-beat:0,30000

```

It would be great if could you help me overcome this issue.

**Comment by shinigami1992** [comment]
I've found the problem was related to this code:

```
 if ((_ref = headers.version) !== Stomp.VERSIONS.V1_1 && _ref !== Stomp.VERSIONS.V1_2) {
    return;
 }
```

when I comment it in react-native environment every things work fine again.

**Comment by Malikkhoja-zz** [comment]
Hi @shinigami1992,

I am getting this error now:
Opening Web Socket...
LOG      Web Socket Opened...
LOG      >>> CONNECT accept-version:1.1,1.0
heart-beat:5000,5000

LOG      Whoops! Lost connection to url.

I checked your answer, and commented the code but it doesnt help. Still the same problem 

Lib Version:
  "sockjs-client": "1.4.0",
    "stompjs": "2.3.3",

Can u help?
Thanks in advance

**Comment by nileio** [comment]
check your timeout settings on the server side
