### ISSUE TITLE
Can't work with RabbitMQ 3.1.3

### ISSUE THREAD

**Issue by leedonpark1975** [jmesnil/stomp-websocket#37]
Hi, I'm testing stomp-websocket with RabbitMQ 3.1.3.  I've already installed the Web-Stomp plugin - http://www.rabbitmq.com/web-stomp.html and got it working with via the examples provided on the RabbitMQ Web-Stomp plugin page that connects to http://127.0.0.1:15674/stomp.  I'm also able to connect directly to STOMP port at 61613 using Telnet.

However, I'm not able to test it using the examples provided on https://github.com/jmesnil/stomp-websocket.  I tried browsertests using the following config for url using all the ports I can find:

url : "ws://localhost:61623"
url : "ws://localhost:61623/stomp"
url : "ws://localhost:61613"
url : "ws://localhost:61613/stomp"
url : "ws://localhost:15674"
url : "ws://localhost:15674/stomp"

For all the url configured, the test fails at "9. Stomp Connection module: Connect to a valid Stomp server (1, 0, 1)"

P.S. I'm testing using a locally - not via a web server.

**Comment by agtruworth** [comment]
I am using below code to connect with RabbitMQ Stomp 
var ws = new SockJS('http://127.0.0.1:15674/stomp');
var client = Stomp.over(ws);
But I get below error in the browser console 
GET http://localhost:15674/ws/info 404 Not Found

Please suggest
