### ISSUE TITLE
Incorrect content-length with multi-byte utf-8 characters

### ISSUE THREAD

**Issue by JMontupet** [jmesnil/stomp-websocket#44]
I'm using stomp.js to send messages which contain some UTF-8 multibyte characters in their body. But the function 'Frame.prototype.toString' is only valid for single byte encoding characters ( because it use '.length' attribut ) and the header value 'content-length' becomes wrong.

**Comment by yanchhuong** [comment]
where is stomp.js to 2.3.1 ? i have same issue , link file please!!!

**Comment by Polve** [comment]
Check if the new library has the problem https://github.com/JSteunou/webstomp-client
