### ISSUE TITLE
can't create a durable topic subscribers

### ISSUE THREAD

**Issue by greezen** [jmesnil/stomp-websocket#51]
hi jmesnil,
I used the stomp js to create a application,it is connected successful.But I need create a durable topic subscribers,it's seems can't do this.My code is:

```
  var headers = {
    login: login,
    passcode: passcode,
    // additional header
    'client-id': 'my-client-id'
   };
      // the client is notified when it is connected to the server.
      //client.connect(login, passcode, function(frame) {
      client.connect(headers, function(frame) {
        client.debug("connected to Stomp");
        $('#connect').fadeOut({ duration: 'fast' });
        $('#connected').fadeIn();
        client.subscribe(destination, function(message) {
          $("#messages").append("<p>" + message.body + "</p>\n");
        });
      });
      return false;
    }); 
```

can you help me?
Tanks!

**Comment by caterinafalchi94** [comment]
@greezen Can you please show me your code about it?

**Comment by greezen** [comment]
@Catechacha 
use FuseSource\Stomp\Stomp;

$user = getenv("ACTIVEMQ_USER"); 
if( !$user ) $user = "admin";

$password = getenv("ACTIVEMQ_PASSWORD");
if( !$password ) $password = "password";

//$headers["client-id"]='das';
$consumer = new Stomp("tcp://192.168.0.101:61613");
$consumer->sync = false;
//$consumer->setReadTimeout(10);
$consumer->clientId = "tt1";

//var_dump($consumer->clientId);exit;
//var_dump($consumer->getSessionId());exit;
if(!$consumer->isConnected()){
	echo 'begin';
	$consumer->connect($user, $password,array('activemq.subcriptionName'=>'tt1' ));
	// subscribe to the topic
	$consumer->subscribe("/topic/tt1");
}


// receive a message from the topic
$msg = $consumer->readFrame();

// do what you want with the message
if ( $msg != null) {
    echo "Message '$msg->body' received from topic\n";
	$consumer->ack($msg);
} else {
    echo "Failed to receive a message\n";
}
$consumer->unsubscribe('/topic/tt1');
$consumer->disconnect();
