### ISSUE TITLE
Working with JMS Text/Bytes Messages and Stomp

### ISSUE THREAD

**Issue by ghost** [jmesnil/stomp-websocket#63]
According to https://activemq.apache.org/stomp.html header line "content-length" determs which message type JMS client will be accepted.

https://github.com/jmesnil/stomp-websocket/blob/master/lib/stomp.js#L39 has hard code for it. So can it be configurable?

**Comment by shyam2017** [comment]
Able to send the Json message as Text message using below command- Stomp (Python)
conn.send(body=json.dumps(json_content), destination=destination, headers={'amq-msg-type':'text'})
